import { TailwindIndicator } from "@/components/helper/TailwindIndicator";
import "./globals.css";
import Navbar from "@/components/layout/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main className="max-w-7xl mx-auto px-2 lg:px-0 mt-16">{children}</main>
        <TailwindIndicator />
      </body>
    </html>
  );
}
